### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bnevis-i** [spiffe/spire#3217]
Not sure yet what configuration is causing this crash.  Will update when figure it out.

```
time="2022-07-04T03:29:34Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027"
time="2022-07-04T03:29:34Z" level=info msg=Configured admin_ids="[]" data_dir=/opt/spire/.data
time="2022-07-04T03:29:34Z" level=debug msg="Closing catalog" subsystem_name=catalog
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x245cf16]

goroutine 1 [running]:
github.com/spiffe/spire/pkg/server/catalog.(*Repository).Close(0xc0000122d0)
	/spire/pkg/server/catalog/catalog.go:101 +0x76
github.com/spiffe/spire/pkg/server/catalog.Load.func1()
	/spire/pkg/server/catalog/catalog.go:127 +0x27
github.com/spiffe/spire/pkg/server/catalog.Load({0x3533f80, 0xc0004a8a00}, {{0x35490b0, 0xc000366fc0}, {{0xc000439791, 0xa}}, 0xc000603920, {0x353a4f0, 0xc0004a8a40}, 0xc000603f20, ...})
	/spire/pkg/server/catalog/catalog.go:137 +0xa9a
github.com/spiffe/spire/pkg/server.(*Server).loadCatalog(0xc000364a80, {0x3533f80, 0xc0004a8a00}, {0x353a4f0, 0xc0004a8a40}, 0xc000603f20, 0xc0006f95e0, {0x7f58a7bd13f8, 0xc000012240})
	/spire/pkg/server/server.go:252 +0x192
github.com/spiffe/spire/pkg/server.(*Server).run(0xc000364a80, {0x3533f80, 0xc0004a8a00})
	/spire/pkg/server/server.go:107 +0x4cc
github.com/spiffe/spire/pkg/server.(*Server).Run(0xc000364a80, {0x3533f80?, 0xc0004a8a00?})
	/spire/pkg/server/server.go:56 +0x2c
github.com/spiffe/spire/cmd/spire-server/cli/run.(*Command).Run(0xc000603830, {0xc00004e070?, 0x2?, 0x0?})
	/spire/cmd/spire-server/cli/run/run.go:242 +0x205
github.com/mitchellh/cli.(*CLI).Run(0xc0004248c0)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
github.com/spiffe/spire/cmd/spire-server/cli.(*CLI).Run(0xc00048b260, {0xc00004e060, 0x4, 0x4})
	/spire/cmd/spire-server/cli/cli.go:115 +0x937
main.main()
	/spire/cmd/spire-server/main.go:10 +0x66
```

* **Version**: 1.3.1 (from gcr.io)
* **Platform**: Linux
* **Subsystem**: server

**Comment by amartinezfayo** [comment]
Thank you @bnevis-i for reporting this.
We have identified this bug in 1.3.1, which caused a panic if there was a plugin configuration error in the server.
This has been addressed in #3166, which has been merged in the main branch and will be included in the next SPIRE release. Please feel free to reopen this issue if you don't see it fixed in the upcoming release.
