### ISSUE TITLE
SEGV error if runnning a binary statically linking glibc

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#3637]
* **Version**: 1.5.1
* **Platform**: Ubuntu 20.04 `Linux 753a6d382ec1 5.15.49-linuxkit` 
* **Subsystem**: agent

If I run a binary built(`make build-static`) statically linking glibc, I get a SEGV error on cgo call.

https://github.com/golang/go/issues/13470 (https://sourceware.org/bugzilla/show_bug.cgi?id=19341)
The above issue could be a factor.

Comments at https://github.com/spiffe/spire/issues/3596 mean that SPIRE does not support link glibc statically? 

error log
```
WARN[0000] Current umask 0022 is too permissive; setting umask 0027 
INFO[0000] Starting agent with data directory: "./data/agent" 
INFO[0000] Plugin loaded                                 external=false plugin_name=disk plugin_type=KeyManager subsystem_name=catalog
INFO[0000] Plugin loaded                                 external=false plugin_name=join_token plugin_type=NodeAttestor subsystem_name=catalog
INFO[0000] Plugin loaded                                 external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
INFO[0000] Bundle loaded                                 subsystem_name=attestor trust_domain_id="spiffe://example.org"
INFO[0000] SVID loaded                                   spiffe_id="spiffe://example.org/spire/agent/join_token/1e9a19e8-4086-47be-9d70-7ad947099a93" subsystem_name=attestor trust_domain_id="spiffe://example.org"
DEBU[0000] Bundle updated                                subsystem_name=cache_manager trust_domain_id=example.org
DEBU[0000] Entry created                                 entry=3fd37b29-d5c3-4324-bcb4-9c1ce594bb17 selectors_added=1 spiffe_id="spiffe://example.org/test" subsystem_name=cache_manager
DEBU[0000] Renewing stale entries                        cache_type=workload count=1 limit=500 subsystem_name=manager
INFO[0000] Renewing X509-SVID                            spiffe_id="spiffe://example.org/test" subsystem_name=manager
DEBU[0000] SVID updated                                  entry=3fd37b29-d5c3-4324-bcb4-9c1ce594bb17 spiffe_id="spiffe://example.org/test" subsystem_name=cache_manager
DEBU[0000] Bundle added                                  subsystem_name=svid_store_cache trust_domain_id=example.org
INFO[0000] Starting Workload and SDS APIs                address=/tmp/spire-agent/public/api.sock network=unix subsystem_name=endpoints
DEBU[0001] Initializing health checkers                  subsystem_name=health
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f038845762f]
runtime stack:
runtime.throw({0x18b1864?, 0x7f0344000d49?})
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/runtime/panic.go:1047 +0x5d fp=0x7f0383ffeb20 sp=0x7f0383ffeaf0 pc=0x43bd5d
runtime.sigpanic()
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/runtime/signal_unix.go:819 +0x369 fp=0x7f0383ffeb70 sp=0x7f0383ffeb20 pc=0x4527e9

goroutine 157 [syscall]:
runtime.cgocall(0x13ca920, 0xc0008e54d0)
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/runtime/cgocall.go:158 +0x5c fp=0xc0008e54a8 sp=0xc0008e5470 pc=0x405a7c
os/user._Cfunc_mygetgrgid_r(0x0, 0xc0006087a0, 0x7f0364000b60, 0x400, 0xc0003109d8)
        _cgo_gotypes.go:109 +0x4c fp=0xc0008e54d0 sp=0xc0008e54a8 pc=0x5379ec
os/user.lookupUnixGid.func1.1(0x0, 0xc000333000?, 0xc0008e5568?, 0x40fa27?)
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/os/user/cgo_lookup_unix.go:176 +0xa6 fp=0xc0008e5530 sp=0xc0008e54d0 pc=0x538ea6
os/user.lookupUnixGid.func1()
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/os/user/cgo_lookup_unix.go:176 +0x29 fp=0xc0008e5560 sp=0xc0008e5530 pc=0x538de9
os/user.retryWithBuffer(0xc000413bd0, 0xc0008e5640)
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/os/user/cgo_lookup_unix.go:244 +0x39 fp=0xc0008e55a8 sp=0xc0008e5560 pc=0x539399
os/user.lookupUnixGid(0x0)
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/os/user/cgo_lookup_unix.go:169 +0x10f fp=0xc0008e5680 sp=0xc0008e55a8 pc=0x538bef
os/user.lookupGroupId({0x26cf4a0?, 0x454154?})
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/os/user/cgo_lookup_unix.go:159 +0x36 fp=0xc0008e56a0 sp=0xc0008e5680 pc=0x538ab6
os/user.LookupGroupId({0x26cf4a0?, 0xc000994000?})
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/os/user/lookup.go:57 +0x1e fp=0xc0008e56c0 sp=0xc0008e56a0 pc=0x5377de
github.com/spiffe/spire/pkg/agent/plugin/workloadattestor/unix.(*Plugin).getGroupName(0xc00058ea20, {0x26cf4a0, 0x1})
        /spire-1.5.1/pkg/agent/plugin/workloadattestor/unix/unix_posix.go:262 +0x36 fp=0xc0008e5718 sp=0xc0008e56c0 pc=0x10b4536
github.com/spiffe/spire/pkg/agent/plugin/workloadattestor/unix.(*Plugin).Attest(0xc00058ea20, {0x40f6df?, 0x203000?}, 0xc0009b9140)
        /spire-1.5.1/pkg/agent/plugin/workloadattestor/unix/unix_posix.go:152 +0x525 fp=0xc0008e5928 sp=0xc0008e5718 pc=0x10b3185
github.com/spiffe/spire-plugin-sdk/proto/spire/plugin/agent/workloadattestor/v1._WorkloadAttestor_Attest_Handler.func1({0x1ae6540, 0xc0009b9110}, {0x16f8da0?, 0xc0009b9140})
        /root/go/pkg/mod/github.com/spiffe/spire-plugin-sdk@v1.4.1-0.20220912221658-c42ab2d657f6/proto/spire/plugin/agent/workloadattestor/v1/workloadattestor_grpc.pb.go:94 +0x78 fp=0xc0008e5968 sp=0xc0008e5928 pc=0xafdf78
github.com/spiffe/spire/pkg/common/catalog.unaryPanicInterceptor({0x1ae6540?, 0xc0009b9110?}, {0x16f8da0?, 0xc0009b9140?}, 0xc000390a20?, 0x160eec0?)
        /spire-1.5.1/pkg/common/catalog/host.go:56 +0x82 fp=0xc0008e59d8 sp=0xc0008e5968 pc=0xae7942
github.com/spiffe/spire-plugin-sdk/proto/spire/plugin/agent/workloadattestor/v1._WorkloadAttestor_Attest_Handler({0x17cd380?, 0xc00058ea20}, {0x1ae6540, 0xc0009b9110}, 0xc0004592d0, 0x192e100)
        /root/go/pkg/mod/github.com/spiffe/spire-plugin-sdk@v1.4.1-0.20220912221658-c42ab2d657f6/proto/spire/plugin/agent/workloadattestor/v1/workloadattestor_grpc.pb.go:96 +0x138 fp=0xc0008e5a30 sp=0xc0008e59d8 pc=0xafde38
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f6b40, {0x1aed540, 0xc000582ea0}, 0xc0009bca20, 0xc00033cae0, 0x2665b10, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23 fp=0xc0008e5e48 sp=0xc0008e5a30 pc=0x92a503
google.golang.org/grpc.(*Server).handleStream(0xc0001f6b40, {0x1aed540, 0xc000582ea0}, 0xc0009bca20, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f fp=0xc0008e5f68 sp=0xc0008e5e48 pc=0x92f5af
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /root/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:965 +0x98 fp=0xc0008e5fe0 sp=0xc0008e5f68 pc=0x927f98
runtime.goexit()
        /spire-1.5.1/.build/linux-x86_64/go/1.19.3/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0008e5fe8 sp=0xc0008e5fe0 pc=0x470221
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

... snip ...

```

glic version
```
# /lib/x86_64-linux-gnu/libc.so.6 
GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.9) stable release version 2.31.
```

**Comment by azdagron** [comment]
Hi @hiyosi! Unfortunately there are many problems statically linking glibc, and it is a generally discouraged practice. 
I don't think we intend to support statically linking to glibc. The `build-static` target was introduced for building binaries that statically link to musl for our scratch images.

The diagnostics here could be better however. We should probably figure out how to prevent the build from happening if its going to statically link against glibc.

**Comment by hiyosi** [comment]
Thank you for a reply!

> Unfortunately there are many problems statically linking glibc, and it is a generally discouraged practice.
I don't think we intend to support statically linking to glibc.

I understand the above.  I think if the policy is clear, there is no problem.

> We should probably figure out how to prevent the build from happening if its going to statically link against glibc.

I think this is a good thing for us to prevent errors.

**Comment by amartinezfayo** [comment]
Hey @hiyosi thank you for bringing this up. Would be awesome if you can open a PR adding a comment in the Makefile to address this. Thank you!
