### ISSUE TITLE
Flaky agent LRU cache tests

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3739]
```
panic: test timed out after 1m0s

goroutine 54 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.4/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001f44e0, {0xdcc43a, 0x1e}, 0xdff450)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc0001f44e0, 0xc000143ba0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x217
testing.runTests(0xc0001ea5a0?, {0x131df20, 0x2b, 0x2b}, {0x40?, 0x7f2418f84ff8?, 0x1329400?})
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc0001ea5a0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:135 +0x2ea

goroutine 53 [select]:
github.com/spiffe/spire/pkg/agent/manager/cache.(*LRUCache).subscribeToWorkloadUpdates(0xc000[265](https://github.com/spiffe/spire/actions/runs/3829729721/jobs/6558195492#step:5:266)7c0, {0xee6bd0, 0xc000040148}, {0xc000214720, 0x1, 0x1}, 0xc00037df88)
	/home/runner/work/spire/spire/pkg/agent/manager/cache/lru_cache.go:531 +0x298
github.com/spiffe/spire/pkg/agent/manager/cache.TestSubscribeToLRUCacheChanges.func2()
	/home/runner/work/spire/spire/pkg/agent/manager/cache/lru_cache_test.go:812 +0x10c
created by github.com/spiffe/spire/pkg/agent/manager/cache.TestSubscribeToLRUCacheChanges
	/home/runner/work/spire/spire/pkg/agent/manager/cache/lru_cache_test.go:811 +0x70b

goroutine 51 [chan receive]:
github.com/spiffe/spire/pkg/agent/manager/cache.TestSubscribeToLRUCacheChanges(0x0?)
	/home/runner/work/spire/spire/pkg/agent/manager/cache/lru_cache_test.go:844 +0xa45
testing.tRunner(0xc00035c4e0, 0xdff450)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1493 +0x75e
FAIL	github.com/spiffe/spire/pkg/agent/manager/cache	60.082s
```

**Comment by Vishal-Chdhry** [comment]
Hi! I am new here and I would love to contribute, can I work on this?

**Comment by amartinezfayo** [comment]
Hi @Vishal-Chdhry, that would be great, thank you!

**Comment by prasadborole1** [comment]
Apologies @Vishal-Chdhry! Didn't realize that you had already picked this issue.
