### ISSUE TITLE
Spire-agent hangs on shutdown when using envoy sds

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#787]
* **Version**: 7933f8d89f3f4b270481ddecc155c0a5ac32d8a6
* **Platform**: macOS 10.14.3
* **Subsystem**: agent

If I ctrl-c the spire-agent while there's an Envoy running connected to SDS, the agent appears to partially shut down, but doesn't actually shut down til the envoy is killed off.

I haven't tested thoroughly yet so it's possible I'm doing something wrong or this is expected behavior, but I felt it worth writing down.

Agent log:

```WARN[0000] Current umask 0022 is too permissive; setting umask 0027.
INFO[0000] data directory: "./.data"
INFO[0000] Starting plugin catalog                       subsystem_name=catalog
DEBU[0000] KeyManager(memory): configuring plugin        subsystem_name=catalog
DEBU[0000] WorkloadAttestor(k8s): configuring plugin     subsystem_name=catalog
DEBU[0000] WorkloadAttestor(unix): configuring plugin    subsystem_name=catalog
DEBU[0000] WorkloadAttestor(docker): configuring plugin  subsystem_name=catalog
DEBU[0000] NodeAttestor(join_token): configuring plugin  subsystem_name=catalog
DEBU[0000] Requesting SVID for spiffe://example.org/agent  subsystem_name=manager
DEBU[0000] Requesting SVID for spiffe://example.org/workload  subsystem_name=manager
INFO[0000] Starting workload API                         subsystem_name=endpoints
DEBU[0006] PID 9025 attested to have selectors [type:"unix" value:"uid:501"  type:"unix" value:"user:mmc"  type:"unix" value:"gid:20"  type:"unix" value:"group:staff" ]  subsystem_name=endpoints
DEBU[0006] PID 9025 attested to have selectors [type:"unix" value:"uid:501"  type:"unix" value:"user:mmc"  type:"unix" value:"gid:20"  type:"unix" value:"group:staff" ]  subsystem_name=endpoints
DEBU[0006] Received StreamSecrets request                nonce= resource_names="[spiffe://example.org/workload]" subsystem_name=sds_api version_info=
DEBU[0006] Received StreamSecrets request                nonce= resource_names="[spiffe://example.org]" subsystem_name=sds_api version_info=
DEBU[0006] Sending StreamSecrets response                count=1 nonce=9078b843 subsystem_name=sds_api version_info="2019-03-08T08:06:33.016294Z"
DEBU[0006] Sending StreamSecrets response                count=1 nonce=14236864 subsystem_name=sds_api version_info="2019-03-08T08:06:33.016234Z"
DEBU[0006] Received StreamSecrets request                nonce=14236864 resource_names="[spiffe://example.org/workload]" subsystem_name=sds_api version_info="2019-03-08T08:06:33.016234Z"
DEBU[0006] Received StreamSecrets request                nonce=9078b843 resource_names="[spiffe://example.org]" subsystem_name=sds_api version_info="2019-03-08T08:06:33.016294Z"
```
^C pressed here

```
INFO[0025] Stopping workload API                         subsystem_name=endpoints
DEBU[0025] Stopping SVID rotator                         subsystem_name=manager
INFO[0025] cache manager stopped                         subsystem_name=manager
```
hung at this state  -- after a bit I hit ctrl-c on envoy too, and it continued:
```
INFO[0052] Stopping plugin catalog                       subsystem_name=catalog
2019/03/08 00:07:18 [DEBUG] plugin: waiting for all plugin processes to complete...
INFO[0052] Agent stopped gracefully
```

**Comment by ZymoticB** [comment]
I noticed this more generically with "a workload connected to the workload API" preventing a spire-agent restart.

**Comment by azdagron** [comment]
I'm pretty sure this a case of the Stop() method on the *grpc.Server not returning while there are open streams.

**Comment by ZymoticB** [comment]
https://godoc.org/google.golang.org/grpc#Server.Stop

> Stop stops the gRPC server. It immediately closes all open connections and listeners. It cancels all active RPCs on the server side and the corresponding pending RPCs on the client side will get notified by connection errors.

**Comment by azdagron** [comment]
Right, I was confusing Stop() with GracefulStop().

**Comment by ZymoticB** [comment]
@mcpherrinm I'm in the middle of a large rebase in our automation so it will be a bit of toil to set up a test env for this, feel free to see if #788 resolves this for you.

**Comment by azdagron** [comment]
#797 removes the machinery that waits for server.Serve() to return, but only for the server. @mcpherrinm's issue was specifically on the agent.

**Comment by ZymoticB** [comment]
arggg, I was in the wrong package! Let me check if the same issue exists on the agent side and show into my draft PR

**Comment by ZymoticB** [comment]
At a glance the agent stop logic was doing the same thing, I updated #788

**Comment by azdagron** [comment]
This is pretty trivial to repro. I took a look at this at one point in time. I now remember why my brain said `Stop()` didn't work. Turns out, `Stop()` gets blocked calling `Close()` on the `*net.UnixListener`.

**Comment by azdagron** [comment]
Hmm. Nope, it's not blocking on the listener. It's blocked closing the unix Conn on the http2 transport.

**Comment by azdagron** [comment]
```
goroutine 82 [semacquire]:
internal/poll.runtime_Semacquire(0xc0004a6328)
        /Users/azdagron/s/spire/.build-darwin-x86_64/src/runtime/sema.go:61 +0x39
internal/poll.(*FD).Close(0xc0004a6300, 0xc0004a6300, 0x0)
        /Users/azdagron/s/spire/.build-darwin-x86_64/src/internal/poll/fd_unix.go:109 +0x90
net.(*netFD).Close(0xc0004a6300, 0xc0003c9640, 0x4188e01)
        /Users/azdagron/s/spire/.build-darwin-x86_64/src/net/fd_unix.go:184 +0x4f
net.(*conn).Close(0xc0004a8000, 0x0, 0x0)
        /Users/azdagron/s/spire/.build-darwin-x86_64/src/net/net.go:201 +0x4b
google.golang.org/grpc/internal/transport.(*http2Server).Close(0xc000364000, 0xc000618930, 0xc000684d80)
        /Users/azdagron/gopath/pkg/mod/google.golang.org/grpc@v1.14.0/internal/transport/http2_server.go:1007 +0xe4
google.golang.org/grpc.(*Server).Stop(0xc0006148c0)
        /Users/azdagron/gopath/pkg/mod/google.golang.org/grpc@v1.14.0/server.go:1352 +0x232
github.com/spiffe/spire/pkg/agent/endpoints.(*endpoints).ListenAndServe(0xc0000cc158, 0x4d75660, 0xc0000c0ac0, 0x0, 0x0)
        /Users/azdagron/s/spire/pkg/agent/endpoints/endpoints.go:58 +0x351
github.com/spiffe/spire/pkg/common/util.RunTasks.func2(0xc000592040, 0x0, 0x0)
        /Users/azdagron/s/spire/pkg/common/util/task.go:37 +0x90
created by github.com/spiffe/spire/pkg/common/util.RunTasks
        /Users/azdagron/s/spire/pkg/common/util/task.go:42 +0x195
```

**Comment by azdagron** [comment]
Turns out the way the agent pulls the peer PID from the UDS connection ends up putting the file descriptor in blocking mode, which messes with closing.
