### ISSUE TITLE
Panic in AWS Node Attestor

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#800]
I saw this panic last night but haven't investigated further.  Filing an issue to keep track

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb175d8]

goroutine 39 [running]:
github.com/aws/aws-sdk-go/aws/request.(*Request).ApplyOptions(0xc00015d000, 0xc00012e120, 0x1, 0x1)
	/go/src/github.com/spiffe/spire/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:192 +0x38
github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeInstancesWithContext(0xc00012e110, 0x7f85461aa168, 0xc00012a500, 0xc00013dd10, 0xc00012e120, 0x1, 0x1, 0x0, 0x0, 0x1)
	/go/src/github.com/spiffe/spire/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go:10995 +0x18b
github.com/spiffe/spire/pkg/server/plugin/nodeattestor/aws.(*IIDAttestorPlugin).ec2Attestation(0xc0003ba840, 0x1fdfb60, 0xc00012a500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/spiffe/spire/pkg/server/plugin/nodeattestor/aws/iid.go:253 +0x38c
github.com/spiffe/spire/pkg/server/plugin/nodeattestor/aws.(*IIDAttestorPlugin).Attest(0xc0003ba840, 0x1fd86a0, 0xc0001182c0, 0xc0001182c0, 0x1)
	/go/src/github.com/spiffe/spire/pkg/server/plugin/nodeattestor/aws/iid.go:139 +0xb7b
github.com/spiffe/spire/proto/server/nodeattestor.BuiltIn.Attest.func1(0x1fe01a0, 0xc00038c690, 0x1fcc160, 0xc0003ba840)
	/go/src/github.com/spiffe/spire/proto/server/nodeattestor/nodeattestor.go:98 +0x89
created by github.com/spiffe/spire/proto/server/nodeattestor.BuiltIn.Attest
	/go/src/github.com/spiffe/spire/proto/server/nodeattestor/nodeattestor.go:97 +0x1a7
```

**Comment by azdagron** [comment]
Looks like this was broken by #747.  The culprit is the `nil` being passed into DescribeInstancesWithContext as the variadic options parameter. Fix incoming.
